export const dataList = {
    'code': 0,
    'msg': '操作成功',
    'ts': 1634729181799,
    'logid': 1634729181799,
    'data': [
        {
            'roadName': '雄安-容城东',
            'stakeCode': null,
            'startStake': 'K96',
            'endStake': 'K82+513',
            'roadDirNo': null,
            'type': null,
            'eventCnt': 4,
            'datetime': '2020',
            'stepIndex': null,
            'id': '4d3ec55e-ab66-4221-bd6c-886a55cf141f',
        },
        {
            'roadName': '雄安-容城东',
            'stakeCode': null,
            'startStake': 'K96',
            'endStake': 'K82+513',
            'roadDirNo': null,
            'type': null,
            'eventCnt': 4,
            'datetime': '2021',
            'stepIndex': null,
            'id': '8b91abc9-3eec-42fe-a7fb-4fa70148e17a',
        },
        {
            'roadName': '高碑店东-东湾枢纽',
            'stakeCode': null,
            'startStake': 'K96',
            'endStake': 'K82+513',
            'roadDirNo': null,
            'type': null,
            'eventCnt': 4,
            'datetime': '2020',
            'stepIndex': null,
            'id': '5476dfcd-9bee-4047-bbb6-62400d602128',
        },
        {
            'roadName': '高碑店东-东湾枢纽',
            'stakeCode': null,
            'startStake': 'K96',
            'endStake': 'K82+513',
            'roadDirNo': null,
            'type': null,
            'eventCnt': 4,
            'datetime': '2021',
            'stepIndex': null,
            'id': 'ad671ed6-8bc3-4ac2-a800-4f1226b4f83d',
        },
    ],
};