export const liveTrafficMock = [
    {
        name: '北京方向',
        data: [20, 350, 300, 300, 200, 400, 350, 400, 300],
    },
    {
        name: '雄安方向',
        data: [400, 450, 500, 400, 350, 400, 400, 500, 500],
    },
];

export const compositeIndicatorMock = {
    name: '路网运行综合指标监控',
    data: [20, 350, 300, 300, 200, 400, 350, 400, 300],
};

export const CARDS_DATA = [
    {
        'id': 28,
        'createAt': null,
        'createTime': null,
        'updateAt': null,
        'updateTime': null,
        'state': null,
        'cardName': 'tpl_bda_weather',
        'styleGroupId': 3,
        'tableInfoId': 1,
        'defaultStyleId': 2,
        'isDefault': 2,
        'subjectIndex': 1,
        'pagelocationIndex': 1,
        'cardWidth': 2,
        'cardHeight': 2,
        'styleGroupCode': 'C',
        'defaultStyleName': '柱状图',
        'tableName': 'tpl_bda_weather_h',
        'bdaTableInfoEntityList': [
            {
                'id': 1,
                'createAt': '1',
                'createTime': '2021-08-25 20:22:01',
                'updateAt': null,
                'updateTime': null,
                'state': 0,
                'tableName': 'tpl_bda_weather_h',
                'tableDescribe': '路网专题-环境气象预警',
                'styleGroupId': 3,
                'xaxisCompany': null,
                'yaxisCompany': '米',
                'xaxisDescribe': '设备桩号',
                'yaxisDescribe': '能见度',
                'queryUrl': 'ihs/analysis/weather/selectweather',
                'isField': 1,
                'obtainFieldUrl': null,
                'batchField': null,
                'typeField': null,
                'bdaDataStyleEntityList': [
                    {
                        'id': 1,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '饼状图',
                        'styleCode': '1',
                    },
                    {
                        'id': 2,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '柱状图',
                        'styleCode': '2',
                    },
                    {
                        'id': 3,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '折线图',
                        'styleCode': '3',
                    },
                    {
                        'id': 4,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '面积图',
                        'styleCode': '4',
                    },
                    {
                        'id': 5,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '条形图',
                        'styleCode': '5',
                    },
                    {
                        'id': 6,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '圆环图',
                        'styleCode': '6',
                    },
                    {
                        'id': 10,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '散点图',
                        'styleCode': '10',
                    },
                    {
                        'id': 12,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '雷达图',
                        'styleCode': '12',
                    },
                ],
                'batchLength': 8,
            },
            {
                'id': 2,
                'createAt': null,
                'createTime': null,
                'updateAt': null,
                'updateTime': null,
                'state': 0,
                'tableName': 'tpl_bda_anomalous_event_d',
                'tableDescribe': '路网专题-交通异常事件',
                'styleGroupId': 3,
                'xaxisCompany': null,
                'yaxisCompany': '件',
                'xaxisDescribe': '事件类型',
                'yaxisDescribe': '事件个数',
                'queryUrl': '',
                'isField': 1,
                'obtainFieldUrl': null,
                'batchField': null,
                'typeField': null,
                'bdaDataStyleEntityList': [
                    {
                        'id': 1,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '饼状图',
                        'styleCode': '1',
                    },
                    {
                        'id': 2,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '柱状图',
                        'styleCode': '2',
                    },
                    {
                        'id': 3,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '折线图',
                        'styleCode': '3',
                    },
                    {
                        'id': 4,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '面积图',
                        'styleCode': '4',
                    },
                    {
                        'id': 5,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '条形图',
                        'styleCode': '5',
                    },
                    {
                        'id': 6,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '圆环图',
                        'styleCode': '6',
                    },
                    {
                        'id': 10,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '散点图',
                        'styleCode': '10',
                    },
                    {
                        'id': 12,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '雷达图',
                        'styleCode': '12',
                    },
                ],
                'batchLength': 8,
            },
        ],
    },
    {
        'id': 29,
        'createAt': null,
        'createTime': null,
        'updateAt': null,
        'updateTime': null,
        'state': null,
        'cardName': 'tpl_bda_anomalous_event_d',
        'styleGroupId': 3,
        'tableInfoId': 2,
        'defaultStyleId': 4,
        'isDefault': 2,
        'subjectIndex': 1,
        'pagelocationIndex': 3,
        'cardWidth': 2,
        'cardHeight': 2,
        'styleGroupCode': 'C',
        'defaultStyleName': '面积图',
        'tableName': 'tpl_bda_anomalous_event_d',
        'bdaTableInfoEntityList': [
            {
                'id': 1,
                'createAt': '1',
                'createTime': '2021-08-25 20:22:01',
                'updateAt': null,
                'updateTime': null,
                'state': 0,
                'tableName': 'tpl_bda_weather_h',
                'tableDescribe': '路网专题-环境气象预警',
                'styleGroupId': 3,
                'xaxisCompany': null,
                'yaxisCompany': '米',
                'xaxisDescribe': '设备桩号',
                'yaxisDescribe': '能见度',
                'queryUrl': 'ihs/analysis/weather/selectweather',
                'isField': 1,
                'obtainFieldUrl': null,
                'batchField': null,
                'typeField': null,
                'bdaDataStyleEntityList': [
                    {
                        'id': 1,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '饼状图',
                        'styleCode': '1',
                    },
                    {
                        'id': 2,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '柱状图',
                        'styleCode': '2',
                    },
                    {
                        'id': 3,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '折线图',
                        'styleCode': '3',
                    },
                    {
                        'id': 4,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '面积图',
                        'styleCode': '4',
                    },
                    {
                        'id': 5,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '条形图',
                        'styleCode': '5',
                    },
                    {
                        'id': 6,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '圆环图',
                        'styleCode': '6',
                    },
                    {
                        'id': 10,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '散点图',
                        'styleCode': '10',
                    },
                    {
                        'id': 12,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '雷达图',
                        'styleCode': '12',
                    },
                ],
                'batchLength': 8,
            },
            {
                'id': 2,
                'createAt': null,
                'createTime': null,
                'updateAt': null,
                'updateTime': null,
                'state': 0,
                'tableName': 'tpl_bda_anomalous_event_d',
                'tableDescribe': '路网专题-交通异常事件',
                'styleGroupId': 3,
                'xaxisCompany': null,
                'yaxisCompany': '件',
                'xaxisDescribe': '事件类型',
                'yaxisDescribe': '事件个数',
                'queryUrl': '',
                'isField': 1,
                'obtainFieldUrl': null,
                'batchField': null,
                'typeField': null,
                'bdaDataStyleEntityList': [
                    {
                        'id': 1,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '饼状图',
                        'styleCode': '1',
                    },
                    {
                        'id': 2,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '柱状图',
                        'styleCode': '2',
                    },
                    {
                        'id': 3,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '折线图',
                        'styleCode': '3',
                    },
                    {
                        'id': 4,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '面积图',
                        'styleCode': '4',
                    },
                    {
                        'id': 5,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '条形图',
                        'styleCode': '5',
                    },
                    {
                        'id': 6,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '圆环图',
                        'styleCode': '6',
                    },
                    {
                        'id': 10,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '散点图',
                        'styleCode': '10',
                    },
                    {
                        'id': 12,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '雷达图',
                        'styleCode': '12',
                    },
                ],
                'batchLength': 8,
            },
        ],
    },
    {
        'id': 30,
        'createAt': null,
        'createTime': null,
        'updateAt': null,
        'updateTime': null,
        'state': null,
        'cardName': 'tpl_bda_charge_d',
        'styleGroupId': 5,
        'tableInfoId': 3,
        'defaultStyleId': 5,
        'isDefault': 2,
        'subjectIndex': 1,
        'pagelocationIndex': 3,
        'cardWidth': 2,
        'cardHeight': 2,
        'styleGroupCode': 'E',
        'defaultStyleName': '条形图',
        'tableName': 'tpl_bda_charge_d',
        'bdaTableInfoEntityList': [
            {
                'id': 3,
                'createAt': null,
                'createTime': null,
                'updateAt': null,
                'updateTime': null,
                'state': 0,
                'tableName': 'tpl_bda_charge_d',
                'tableDescribe': '路网专题-收费流量监测',
                'styleGroupId': 5,
                'xaxisCompany': '月日',
                'yaxisCompany': '辆',
                'xaxisDescribe': '时间',
                'yaxisDescribe': '交通量',
                'queryUrl': '',
                'isField': 1,
                'obtainFieldUrl': null,
                'batchField': null,
                'typeField': null,
                'bdaDataStyleEntityList': [
                    {
                        'id': 2,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '柱状图',
                        'styleCode': '2',
                    },
                    {
                        'id': 3,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '折线图',
                        'styleCode': '3',
                    },
                    {
                        'id': 4,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '面积图',
                        'styleCode': '4',
                    },
                    {
                        'id': 5,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '条形图',
                        'styleCode': '5',
                    },
                    {
                        'id': 10,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '散点图',
                        'styleCode': '10',
                    },
                    {
                        'id': 12,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '雷达图',
                        'styleCode': '12',
                    },
                ],
                'batchLength': 6,
            },
        ],
    },
    {
        'id': 31,
        'createAt': null,
        'createTime': null,
        'updateAt': null,
        'updateTime': null,
        'state': null,
        'cardName': 'tpl_bda_indicator_d',
        'styleGroupId': 1,
        'tableInfoId': 4,
        'defaultStyleId': 4,
        'isDefault': 2,
        'subjectIndex': 1,
        'pagelocationIndex': 4,
        'cardWidth': 2,
        'cardHeight': 2,
        'styleGroupCode': 'A',
        'defaultStyleName': '面积图',
        'tableName': 'tpl_bda_indicator_d',
        'bdaTableInfoEntityList': [
            {
                'id': 4,
                'createAt': null,
                'createTime': null,
                'updateAt': null,
                'updateTime': null,
                'state': 0,
                'tableName': 'tpl_bda_indicator_d',
                'tableDescribe': '路网运行综合指标监控',
                'styleGroupId': 1,
                'xaxisCompany': 'h',
                'yaxisCompany': '',
                'xaxisDescribe': '时间',
                'yaxisDescribe': '拥堵指数',
                'queryUrl': '',
                'isField': 1,
                'obtainFieldUrl': null,
                'batchField': null,
                'typeField': null,
                'bdaDataStyleEntityList': [
                    {
                        'id': 2,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '柱状图',
                        'styleCode': '2',
                    },
                    {
                        'id': 3,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '折线图',
                        'styleCode': '3',
                    },
                    {
                        'id': 4,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '面积图',
                        'styleCode': '4',
                    },
                    {
                        'id': 5,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '条形图',
                        'styleCode': '5',
                    },
                    {
                        'id': 10,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '散点图',
                        'styleCode': '10',
                    },
                    {
                        'id': 12,
                        'createAt': null,
                        'createTime': null,
                        'updateAt': null,
                        'updateTime': null,
                        'state': 0,
                        'styleName': '雷达图',
                        'styleCode': '12',
                    },
                ],
                'batchLength': 8,
            },
        ],
    },
];